### ISSUE TITLE
Missing locks on write/read on redis

### ISSUE THREAD

**Issue by fabiocicerchia** [fabiocicerchia/go-proxy-cache#45]
Make sure there won't be any data race while one request is writing data to Redis and another one is reading the same keys.
It would be helpful to implement a locking system like:
- https://redis.io/commands/setnx
- https://github.com/go-redsync/redsync

The lock should not be on the client as a whole, but should be on the key:
 - reads on 2 different keys: allowed
 - reads on the same key: allowed
 - writes on 2 different keys: allowed
 - writes on the same key: blocked

**Comment by krishnaindani** [comment]
Hi, Is this issue available to work on?

**Comment by fabiocicerchia** [comment]
Hi, yes it is available to be picked up. Thank you.

**Comment by krishnaindani** [comment]
Is the plan to use read/write locks across all Redis operations? Would you be able to add a little more description of what are we trying to accomplish here to get a better picture?

**Comment by fabiocicerchia** [comment]
@krishnaindani I've updated the description, hope it makes sense, but I'm always open to suggestions.

**Comment by krishnaindani** [comment]
> @krishnaindani I've updated the description, hope it makes sense, but I'm always open to suggestions.

Thanks, I will go through it and codebase and will reach out if I have any questions/suggestions.

**Comment by fabiocicerchia** [comment]
@krishnaindani if you didn't start working on it yet I could pick it up, as I've got some spare time. Let me know so we don't work on the same issue ;)

**Comment by krishnaindani** [comment]
I started looking into the codebase and thinking about how to do it, but it might take time for me. You can take this, I can take some other issue later.
